#!/usr/bin/env node
// ============================================
// LEXICON — Data Build Script
// Concatenates data/categories.js + every
// data/entries/*.js + data/index.js into a
// single data.bundle.js that index.html loads.
//
// Run this after adding/editing any category
// or entry file:
//   node build-data.js
//
// Why a build step instead of 30+ <script> tags:
// keeps editing scoped to one small file per
// category (safe, scalable, easy to diff) while
// shipping a single fast-loading, cacheable file
// to the actual app — important for a PWA on
// Android where every extra request costs cold-
// start time.
// ============================================

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, "data");
const ENTRIES_DIR = path.join(DATA_DIR, "entries");
const OUT_FILE = path.join(ROOT, "data.bundle.js");

function readCategoryIds() {
  const content = fs.readFileSync(path.join(DATA_DIR, "categories.js"), "utf8");
  const matches = [...content.matchAll(/id:\s*"([^"]+)"/g)];
  return matches.map(m => m[1]);
}

function build() {
  const ids = readCategoryIds();
  const parts = [];

  parts.push("// ============================================");
  parts.push("// LEXICON — Built Data Bundle (auto-generated)");
  parts.push("// Do NOT edit this file directly — it is");
  parts.push("// regenerated from data/categories.js and");
  parts.push("// data/entries/*.js by build-data.js.");
  parts.push(`// Built: ${new Date().toISOString()}`);
  parts.push("// ============================================\n");

  // 1. Categories registry
  const categoriesSrc = fs.readFileSync(path.join(DATA_DIR, "categories.js"), "utf8");
  parts.push(categoriesSrc);

  // 2. Each category's entries file, in registry order
  const missing = [];
  for (const id of ids) {
    const file = path.join(ENTRIES_DIR, `${id}.js`);
    if (!fs.existsSync(file)) {
      missing.push(id);
      continue;
    }
    parts.push(fs.readFileSync(file, "utf8"));
  }

  if (missing.length) {
    console.error("ERROR: missing entry files for categories:", missing.join(", "));
    process.exit(1);
  }

  // 3. Loader that merges all ENTRIES_<ID> arrays into ENTRIES
  const varNames = ids.map(id => `ENTRIES_${id.toUpperCase()}`);
  parts.push("// ---- merged ENTRIES array ----");
  parts.push("const ENTRIES = [].concat(");
  parts.push(varNames.map((v, i) => `  ${v}${i < varNames.length - 1 ? "," : ""}`).join("\n"));
  parts.push(");");

  fs.writeFileSync(OUT_FILE, parts.join("\n\n"));

  // quick stats
  const totalEntries = varNames.reduce((sum, vn) => {
    const re = new RegExp(`const ${vn} = (\\[[\\s\\S]*?\\]);`, "m");
    return sum;
  }, 0);

  console.log(`Built ${OUT_FILE}`);
  console.log(`Categories: ${ids.length}`);
}

build();
